### ISSUE TITLE
Errors unboxing

### ISSUE THREAD

**Issue by yonni12** [truffle-box/pet-shop-box#12]
I'm getting the following errors from `truffle unbox pet-shop`:

```
Downloading...
Unpacking...
Setting up...
Error: Command failed: npm install
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN ETXTBSY: text file is busy, rmdir '/host/pet-shop-tutorial/node_modules/fsevents/build/Release/.deps/Users/eshanker/Code/fsevents'
npm ERR! path ../dev-ip/lib/dev-ip.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink
npm ERR! EPROTO: protocol error, symlink '../dev-ip/lib/dev-ip.js' -> '/host/pet-shop-tutorial/node_modules/.bin/dev-ip'


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-12-05T13_29_49_590Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

I'm running in an ubuntu xenial virtual machine (vagrant file [here](https://gist.github.com/yonni12/fb9979fa769c940b0df28dd01fa2eddc)).

**Comment by troef** [comment]
The trouble is with Vagrant and symlinks, see this topic https://github.com/npm/npm/issues/7308

What helped me was running `npm install --no-bin-links` or `yarn --no-bin-links`
