### ISSUE TITLE
 Error: Could not find artifacts

### ISSUE THREAD

**Issue by aathorson** [truffle-box/pet-shop-box#23]
Hi all!

**Im running on:**
Windows 10 Enterprise
Truffle v4.1.5 (core: 4.1.5)
Solidity v0.4.21 (solc-js)

**I'm following the pet-shop example and everything goes well untill I run:**
truffle.cmd test

**Then I get:**
Compiling .\contracts\Adoption.sol...
Compiling .\test\TestAdoption.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

**But then:**

 TestAdoption
    1) "before all" hook: prepare suite

  0 passing (3s)
  1 failing

  1) TestAdoption "before all" hook: prepare suite:
     Error: Could not find artifacts for /C/Users/adria.aguillo/pet-shop-tutorial/contracts/Adoption.sol from any sources
 at Resolver.require (C:\Users\adria.aguillo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-resolver\index.js:37:1)
  ...
  ...

**How could I fix this?** 

Thank you very much

**Comment by knzeng-e** [comment]
Hi Everyone!
I'm also following the same tutorial and having the same issue at the same part of the tutorial. I'm running truffle v4.1.14 (core: 4.1.14) and Solidity v0.4.24 (solc-js) on a mac OX Captain 10.11.6 version.

How can I fix this ?

Thank you all!

**Comment by galimba** [comment]
same here, but on linux... even tried different versions for truffle and solidity ‾\_(ツ)_/‾

**Comment by belenmartinsoltel** [comment]
I have the same problem 
Truffle v5.0.0 (core: 5.0.0)
Solidity v0.5.0 (solc-js)
Node v10.14.2
Windows 10

TestAdoption
    1) "before all" hook: prepare suite


  0 passing (8s)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     Error: Could not find artifacts for /C/PROYECTOS/BlockChainDocs/servicechain.git/servicechain/pet-shop-tutorial/contracts/Adoption.sol from
any sources
      at Resolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at dependency_paths.forEach.dependency_path (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)
