### ISSUE TITLE
Issue regarding npm run dev

### ISSUE THREAD

**Issue by Sharma-Hrishabh** [truffle-box/pet-shop-box#36]
When i m trying to run the dapp,an error is being thrown.
I'm new to this solidity stuff,and trying to learn through this pet-shop-box.
Can anyone help me?
Here is the error-:

Browsersync] Serving files from: ./src
[Browsersync] Serving files from: ./build/contracts
[Browsersync] Watching files...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/hrishabh/crypto-pet/migrations/1_initial_migration.js ENOSPC
    at _errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1383:19)
    at Object.fs.watch (fs.js:1409:11)
    at createFsWatchInstance (/home/hrishabh/crypto-pet/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/hrishabh/crypto-pet/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/hrishabh/crypto-pet/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/hrishabh/crypto-pet/node_modules/chokidar/lib/nodefs-handler.js:259:21)
    at FSWatcher.<anonymous> (/home/hrishabh/crypto-pet/node_modules/chokidar/lib/nodefs-handler.js:480:21)
    at FSReqWrap.oncomplete (fs.js:154:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pet-shop@1.0.0 dev: `lite-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pet-shop@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hrishabh/.npm/_logs/2018-12-27T17_56_55_600Z-debug.log
hrishabh@hrishabh-HP-Pavilion-15-Notebook-PC:~/crypto-pet$ npm run serve
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hrishabh/.npm/_logs/2018-12-27T17_57_30_778Z-debug.log

**Comment by Sharma-Hrishabh** [comment]
I'm closing this issue as it was not related to truffle suite,another program was trying to suppress all ports in my linux and now that issue is solved.
