### ISSUE TITLE
Error Downloading Box and Error while init.

### ISSUE THREAD

**Issue by beejay777** [truffle-box/pet-shop-box#37]
```
# truffle unbox pet-shop
Downloading...
Error: Truffle Box at URL https://github.com/truffle-box/pet-shop-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by beejay777** [comment]
Changing truffle from version 4 to 5 solved the problem.
