### ISSUE TITLE
Test - "before all" hook: prepare suite - out of gas.

### ISSUE THREAD

**Issue by prographo** [truffle-box/pet-shop-box#39]
Any ideas?

```
truffle version
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v10.13.0

truffle(develop)> test
Using network 'develop'.

Compiling ./test/TestAdoption.sol...


  TestAdoption
    1) "before all" hook: prepare suite


  0 passing (2s)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     Error: while migrating Assert: Returned error: VM Exception while processing transaction: out of gas
      at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
      at process._tickCallback (internal/process/next_tick.js:68:7)



1
truffle(develop)> 
/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/utils.js:200
      throw new Error(error);
^
Error: TestAdoption contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of TestAdoption: Assert
    at Function.checkLibraries (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/utils.js:200:1)
    at constructor.detectNetwork.then.network (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract.js:181:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by modianar** [comment]
Its an error of gas limit you need to increase the gas limit
First check your account balance :  balance = web3.eth.getBalance(someAddress);
then try to specify the gaslimit contractInstance.createProposal("ADHD", "Foo", 2, {from: web3.eth.accounts[1], gas:3000000})
