### ISSUE TITLE
Strange "hook" error

### ISSUE THREAD

**Issue by HM999** [truffle-box/pet-shop-box#40]
Any idea what the problem is, or how I debug?

```
: truffle test
Using network 'development'.

Compiling ./contracts/Adoption.sol...
Compiling ./test/TestAdoption.sol...


  TestAdoption
    1) "before all" hook: prepare suite


  0 passing (20s)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     Error: while migrating TestAdoption: Returned error: VM Exception while processing transaction: revert
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)


```

This is the Ganache log, it says "revert" but no reason why:

```
[17:24:46]   Transaction: 0xd4f8e47ef6f02036d3880512ffe64545ce08b5e85cc28f2408242efaee272add
[17:24:46]   Contract created: 0x4e96714cc6c51e9b673ec09701e12ac3e27fb9b2
[17:24:46]   Gas usage: 190068
[17:24:46]   Block Number: 16
[17:24:46]   Block Time: Wed Jan 30 2019 17:24:44 GMT+0000 (GMT)
[17:24:46] eth_getTransactionReceipt
[17:24:46] eth_getCode
[17:24:46] eth_getBlockByNumber
[17:24:46] eth_getBlockByNumber
[17:24:46] eth_getBlockByNumber
[17:24:46] eth_estimateGas
[17:24:46] eth_getBlockByNumber
[17:24:46] eth_blockNumber
[17:24:46] eth_sendTransaction
[17:24:46]   Transaction: 0x2995d64ec8cff5018e91e99cf9fb850a4fb3153575e539de2b31998835907c1c
[17:24:46]   Contract created: 0xc43cc30198cf91e1f791bb1d29582e12ada1ceb7
[17:24:46]   Gas usage: 189480
[17:24:46]   Block Number: 17
[17:24:46]   Block Time: Wed Jan 30 2019 17:24:45 GMT+0000 (GMT)
[17:24:46]   Runtime Error: revert
[17:24:46] eth_call
[17:24:46] eth_getBlockByNumber
```

**Comment by modianar** [comment]
You can refer to this link....

https://ethereum.stackexchange.com/questions/47115/truffle-error-vm-exception-while-processing-transaction-revert
