### ISSUE TITLE
DownloadingError: read ECONNRESET     at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)

### ISSUE THREAD

**Issue by ArtieLadie** [truffle-box/pet-shop-box#49]
Ubuntu 18.04.

Truffle v5.1.2 (core: 5.1.2)

Solidity v0.5.12 (solc-js)

Node v13.2.0

Web3.js v1.2.2
________________________________
When I execute `truffle unbox pet-shop` on terminal, I get error 

```
✔ Preparing to download
⠼ DownloadingError: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)
```

I am expecting contents of directory to look like this (from https://www.dappuniversity.com/articles/the-ultimate-ethereum-dapp-tutorial)

<img width="191" alt="expected" src="https://user-images.githubusercontent.com/12385598/70075136-25348f00-15ca-11ea-8eea-860255c54b2f.png">

But instead it looks like this

![unwanted_output](https://user-images.githubusercontent.com/12385598/70075208-49906b80-15ca-11ea-8c16-430bc9daf125.JPG)

**Comment by ArtieLadie** [comment]
If you are behind organizational proxy, clone the repo, i.e.

```
git clone https://github.com/truffle-box/pet-shop-box.git
cd pet-shop-box
rm -rf .git # Remove the .git record 
npm install
```
