### ISSUE TITLE
I am getting the following error from truffle unbox

### ISSUE THREAD

**Issue by muhammadYunas** [truffle-box/pet-shop-box#60]
D:\Dev\Ethereum\contest>truffle unbox pet-shop

Starting unbox...
=================

√ Preparing to download box
× Downloading
Unbox failed!
× Downloading
Unbox failed!
RequestError: Error: getaddrinfo ENOENT raw.githubusercontent.com
    at new RequestError (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.3.2 (core: 5.3.2)
Node v14.16.0

**Comment by cds-amal** [comment]
Hi @muhammadYunas, is this still an issue? I was unable to reproduce this and wonder if you're behind a proxy?

**Comment by muhammadYunas** [comment]
Yes haven’t solved yet

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cds-amal** [comment]
Sorry about that. Are you behind a proxy?

**Comment by muhammadYunas** [comment]
I'm in China some time use it for Google services

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cds-amal** [comment]
You could try adding a hosts entry to resolve `raw.githubusercontent.com`

1. open `C:\Windows\System32\drivers\etc\host` with notepad
2. add `185.199.109.133    raw.githubusercontent.com`
3. save and exit.

**Comment by muhammadYunas** [comment]
Ok I’ll try it thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by muhammadYunas** [comment]
> You could try adding a hosts entry to resolve `raw.githubusercontent.com`
> 
> 1. open `C:\Windows\System32\drivers\etc\host` with notepad
> 2. add `185.199.109.133    raw.githubusercontent.com`
> 3. save and exit.

Yes, it worked for me thank you so much.

**Comment by muhammadYunas** [comment]
> You could try adding a hosts entry to resolve `raw.githubusercontent.com`
> 
> 1. open `C:\Windows\System32\drivers\etc\host` with notepad
> 2. add `185.199.109.133    raw.githubusercontent.com`
> 3. save and exit.

Yes, it worked for me thank you so much.
